### PR TITLE
Deprecate PDO and the connection instance in Doctrine-based adapters

### LINKED ISSUE #534: Deprecate the use of 'pdo' in Doctrine database adapter configuration in Imbo-2.x
Currently the Doctrine database adapters allows the use of a PDO instance in the configuration through the `pdo` config option:

```php
$adapter = new Imbo\Database\Doctrine([
    'pdo' => new PDO(/* ... */);
]);
```

This causes some inconsistencies with regards to exceptions and error handling. This feature will be completely removed in Imbo-3.x, and should be deprecated in Imbo-2.x.

Instead Imbo should rely on the following configuration (used by Doctrine):

```php
$adapter = new Imbo\Database\Doctrine([
    'dbname' => 'database',
    'user' => 'username',
    'password' => 'password',
    'host' => 'hostname',
    'driver' => 'pdo_mysql',
]);
```

### PR DESCRIPTION
**Pull request by christeredvartsen**
This will deprecated the use of PDO directly, and the use of the connection instance in Doctrine-based adapters.

Before the pull request can be merged the following tasks must be finished:

- [x] Fix `Imbo\Database\Doctrine` (675a64b3f73439d3e4406ae3a7722de51da02b7c)
- [x] Fix `Imbo\Storage\Doctrine` (435248aa0358929da30c28572d9b0106c23bd5ab)
- [x] Fix `Imbo\EventListener\ImageVariations\Storage\Doctrine` (3d5483b85c1f50a7946cffb77f5a79d0dc06922e)
- [x] Fix `Imbo\EventListener\ImageVariations\Database\Doctrine` (99cdf558d456ddc4db12269ed579dcab5b3f0708)
- [x] Update docs

Resolves #534.

### CODE REVIEW

File: library/Imbo/Database/Doctrine.php [hunk 1]
```diff
@@ -27,14 +27,6 @@
...
  * Doctrine 2 database driver
  *
- * Parameters for this driver:
- *
- * - <pre>(string) dbname</pre> Name of the database to connect to
- * - <pre>(string) user</pre> Username to use when connecting
- * - <pre>(string) password</pre> Password to use when connecting
- * - <pre>(string) host</pre> Hostname to use when connecting
- * - <pre>(string) driver</pre> Which driver to use
- *
```
Comment (matslindh) [inline library/Imbo/Database/Doctrine.php]: What's the reason for dropping our own documentation of the accepted parameters? We should probably at least link to what Doctrine accepts as parameters?

File: library/Imbo/EventListener/ImageVariations/Database/Doctrine.php [hunk 2]
```diff
@@ -18,15 +18,6 @@
...
  *
- * Valid parameters for this driver:
- *
- * - <pre>(string) dbname</pre> Name of the database to connect to
- * - <pre>(string) user</pre> Username to use when connecting
- * - <pre>(string) password</pre> Password to use when connecting
- * - <pre>(string) host</pre> Hostname to use when connecting
- * - <pre>(string) driver</pre> Which driver to use
- * - <pre>(PDO) pdo</pre> PDO adapter to use, as an alternative to specifying the above
- *
```
Comment (matslindh) [inline library/Imbo/EventListener/ImageVariations/Database/Doctrine.php]: Same here - reference to the Doctrine documentation for accepted parameters?

File: library/Imbo/EventListener/ImageVariations/Storage/Doctrine.php [hunk 3]
```diff
@@ -17,14 +17,6 @@
...
  * Doctrine 2 image variations storage driver
  *
- * Parameters for this driver:
- *
- * - <pre>(string) dbname</pre> Name of the database to connect to
- * - <pre>(string) user</pre> Username to use when connecting
- * - <pre>(string) password</pre> Password to use when connecting
- * - <pre>(string) host</pre> Hostname to use when connecting
- * - <pre>(string) driver</pre> Which driver to use
- *
```
Comment (matslindh) [inline library/Imbo/EventListener/ImageVariations/Storage/Doctrine.php]: Doctrine reference here as well

File: library/Imbo/Storage/Doctrine.php [hunk 4]
```diff
@@ -21,14 +21,6 @@
...
  * Doctrine 2 storage driver
  *
- * Parameters for this driver:
- *
- * - <pre>(string) dbname</pre> Name of the database to connect to
- * - <pre>(string) user</pre> Username to use when connecting
- * - <pre>(string) password</pre> Password to use when connecting
- * - <pre>(string) host</pre> Hostname to use when connecting
- * - <pre>(string) driver</pre> Which driver to use
- *
```
Comment (matslindh) [inline library/Imbo/Storage/Doctrine.php]: Doctrine reference - although we're probably removing the Storage Doctrine drivers in a future PR anyway?

File: tests/phpunit/ImboIntegrationTest/Database/DoctrineTest.php [hunk 5]
```diff
@@ -94,17 +101,4 @@ public function setUp() {
...
-            $this->pdo->query("DROP TABLE IF EXISTS imageinfo");
-            $this->pdo->query("DROP TABLE IF EXISTS metadata");
-            $this->pdo->query("DROP TABLE IF EXISTS shorturl");
-            $this->pdo->query("DROP INDEX IF EXISTS shorturlparams");
-        }
-
-        $this->pdo = null;
-
-        parent::tearDown();
-    }
```
Comment (matslindh) [inline tests/phpunit/ImboIntegrationTest/Database/DoctrineTest.php]: Will the DB file be left in /tmp after the tests has finished?

File: tests/phpunit/ImboIntegrationTest/Database/DoctrineTest.php [hunk 6]
```diff
@@ -21,16 +21,19 @@
  */
 class DoctrineTest extends DatabaseTests {
     /**
-     * @var PDO
+     * Path to the database file
+     *
+     * @var string
      */
-    private $pdo;
+    private $dbPath = '/tmp/imbo-database-doctrine-integration-test.sql';
```
Comment (matslindh) [inline tests/phpunit/ImboIntegrationTest/Database/DoctrineTest.php]: This is not Windows compatible - using `tempnam(sys_get_temp_dir(), ...)` would be better if we can't use :memory:

File: tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Database/DoctrineTest.php [hunk 7]
```diff
@@ -21,16 +21,19 @@
  */
 class DoctrineTest extends DatabaseTests {
     /**
-     * @var PDO
+     * Path to the database file
+     *
+     * @var string
      */
-    private $pdo;
+    private $dbPath = '/tmp/imbo-eventlistener-imagevariations-database-integration-test.sql';
```
Comment (matslindh) [inline tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Database/DoctrineTest.php]: Not Windows-compatible

File: tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Database/DoctrineTest.php [hunk 8]
```diff
@@ -66,16 +70,4 @@ public function setUp() {
...
-     * Clean up after each run
-     */
-    public function tearDown() {
-        if ($this->pdo) {
-            $this->pdo->query('DROP TABLE IF EXISTS imagevariations');
-            $this->pdo = null;
-        }
-
-        parent::tearDown();
-    }
```
Comment (matslindh) [inline tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Database/DoctrineTest.php]: Clean-up of DB file?

File: tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Storage/DoctrineTest.php [hunk 9]
```diff
@@ -21,16 +21,19 @@
  */
 class DoctrineTest extends StorageTests {
     /**
-     * @var PDO
+     * Path to the database file
+     *
+     * @var string
      */
-    private $pdo;
+    private $dbPath = '/tmp/imbo-eventlistener-imagevariations-storage-doctrine-integration-test.sql';
```
Comment (matslindh) [inline tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Storage/DoctrineTest.php]: Not Windows compatible

File: tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Storage/DoctrineTest.php [hunk 10]
```diff
@@ -64,13 +68,4 @@ public function setUp() {
...
     }
-
-    /**
-     * Reset PDO instance after each test
-     */
-    public function tearDown() {
-        $this->pdo = null;
-
-        parent::tearDown();
-    }
```
Comment (matslindh) [inline tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Storage/DoctrineTest.php]: Cleanup of DB file?

File: tests/phpunit/ImboIntegrationTest/Storage/DoctrineTest.php [hunk 11]
```diff
@@ -21,16 +21,20 @@
  */
 class DoctrineTest extends StorageTests {
     /**
-     * @var PDO
+     * Path to the database file
+     *
+     * @var string
      */
-    private $pdo;
+    private $dbPath = '/tmp/imbo-storage-doctrine-integration-test.sql';
```
Comment (matslindh) [inline tests/phpunit/ImboIntegrationTest/Storage/DoctrineTest.php]: Not windows compatible

File: tests/phpunit/ImboIntegrationTest/Storage/DoctrineTest.php [hunk 12]
```diff
@@ -61,10 +66,4 @@ public function setUp() {
 
         parent::setUp();
     }
-
-    public function tearDown() {
-        $this->pdo = null;
-
-        parent::tearDown();
-    }
```
Comment (matslindh) [inline tests/phpunit/ImboIntegrationTest/Storage/DoctrineTest.php]: Cleanup of DB file?

File: library/Imbo/Database/Doctrine.php (hunk 1 above)
Comment (christeredvartsen) [inline library/Imbo/Database/Doctrine.php]: Mostly because each driver can introduce different parameters, so we'd just be duplicating Doctrines documentation. I agree that we could simply add a link to http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html instead.

File: library/Imbo/EventListener/ImageVariations/Database/Doctrine.php (hunk 2 above)
Comment (christeredvartsen) [inline library/Imbo/EventListener/ImageVariations/Database/Doctrine.php]: See above.

File: library/Imbo/EventListener/ImageVariations/Storage/Doctrine.php (hunk 3 above)
Comment (christeredvartsen) [inline library/Imbo/EventListener/ImageVariations/Storage/Doctrine.php]: See above.

File: tests/phpunit/ImboIntegrationTest/Database/DoctrineTest.php (hunk 6 above)
Comment (christeredvartsen) [inline tests/phpunit/ImboIntegrationTest/Database/DoctrineTest.php]: We can't use memory as two instances using `sqlite::memory:` don't share memory space. But I will update this to use `tempnam(sys_get_temp_dir(), ...)`.

File: tests/phpunit/ImboIntegrationTest/Database/DoctrineTest.php (hunk 5 above)
Comment (christeredvartsen) [inline tests/phpunit/ImboIntegrationTest/Database/DoctrineTest.php]: Yup. Will fix.

File: tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Database/DoctrineTest.php (hunk 7 above)
Comment (christeredvartsen) [inline tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Database/DoctrineTest.php]: See above.

File: tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Database/DoctrineTest.php (hunk 8 above)
Comment (christeredvartsen) [inline tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Database/DoctrineTest.php]: Will fix.

File: tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Storage/DoctrineTest.php (hunk 9 above)
Comment (christeredvartsen) [inline tests/phpunit/ImboIntegrationTest/EventListener/ImageVariations/Storage/DoctrineTest.php]: See above.

**Comment by christeredvartsen** [comment]
@matslindh The issues you raised should have been fixed in the last two commits.

**Comment by matslindh** [comment]
👍
