### PR TITLE
Fix race conditions when adding an image

### LINKED ISSUE #521: Suspected race condition in src/Database/Doctrine.php insertImage()
This is all assuming mysql is used.

If the same image is inserted a bunch of times very quickly, I believe there is a race condition. I used to work on a project that occasionally failed to upload images, and I think this is the cause. But I no longer have access to the project or the environment so I cannot say for sure.

Basically, you could end up trying to insert records in mysql with the same imageIdentifier.

Presumably one could easily reproduce by temporarily adding a sleep statement in insertImage()

### PR DESCRIPTION
**Pull request by matslindh**
This is a attempt to fix #521 properly.

Image identificator generation is moved into the Images resource, and each database adapter is responsible for attempting the insert and throwing a `DuplicateImageIdentifierException` if the insert failed because of an unique key constraint violation. I've implemented this for both Mongo adapters and the Doctrine adapter (as long as it's using PDO at least).

The current implementation keeps track of a property named `$updateIfDuplicate` through the events, and this property is based on whether a image generation algorithm is deterministic or not. If the algorithm is deterministic, we'll perform an update if there's a duplicate, while if it's not - we'll generate a new identifier and try again (up to 100 times).

There is one issue we'd need to solve: Any Mongo database doesn't have a unique index applied by default, which would be necessary to avoid the possibility of a race condition when documents are inserted with the Mongo backend. I've added the index creation in the tests, but this needs to be documented (and probably added to a setup script) to configure MongoDB on installation.

### CODE REVIEW

File: src/Database/Mongo.php [hunk 1]
```diff
@@ -156,6 +157,10 @@ public function insertImage($user, $imageIdentifier, Image $image) {
         try {
             $this->getImageCollection()->insertOne($data);
         } catch (MongoException $e) {
+            if (strpos($e->getMessage(), 'E11000 duplicate key error') === 0) {
```
Comment (christeredvartsen) [inline src/Database/Mongo.php]: One way to detect if a unique constraint violation occured is:

```php
try {
    $this->getImageCollection()->insertOne($data);
} catch (MongoException $e) {
    foreach ($e->getWriteResult()->getWriteErrors() as $error) {
        if ($error->getCode() === 11000) {
            throw new DuplicateImageIdentifierException('Duplicate image identifier when attempting to insert image into DB.', 503);
        }
    }

    throw new DatabaseException('Unable to save image data', 500, $e);
}
```

File: src/Resource/Images.php [hunk 2]
```diff
@@ -60,16 +61,53 @@ public function getImages(EventInterface $event) {
...
     public function addImage(EventInterface $event) {
-        $event->getManager()->trigger('db.image.insert');
-        $event->getManager()->trigger('storage.image.insert');
-
         $request = $event->getRequest();
         $response = $event->getResponse();
         $image = $request->getImage();
 
+        // attempt to store the image in the underlying database
+        $maxAttempts = 100;
```
Comment (christeredvartsen) [inline src/Resource/Images.php]: Why `100`?

File: src/Resource/Images.php [hunk 3]
```diff
@@ -60,16 +61,53 @@ public function getImages(EventInterface $event) {
...
+        for ($attempt = 0; $attempt < $maxAttempts; $attempt++) {
+            try {
+                $image->setImageIdentifier($imageIdentifierGenerator->generate($image));
+                $event->getManager()->trigger('db.image.insert', ['updateIfDuplicate' => $imageIdentifierGenerator->isDeterministic()]);
+                break;
+            } catch (DuplicateImageIdentifierException $exception) {
+                // the image identifier already exists - or was created before we inserted
+                // so we retry the event to get the last submitted image
+                if ($imageIdentifierGenerator->isDeterministic()) {
+                    $event->getManager()->trigger('db.image.insert', ['updateIfDuplicate' => $imageIdentifierGenerator->isDeterministic()]);
```
Comment (christeredvartsen) [inline src/Resource/Images.php]: Keep in mind that other event listeners also subscribe to the `db.image.insert` event.

`Imbo\EventListener\ExifMetadata::save()` triggers on this event as well, but with a priority of `-100`, so it requires listeners earlier in the chain to succeed, so that event listener specifically will probably not cause any issues.

File: tests/phpunit/integration/Database/MongoDBTest.php [hunk 4]
```diff
@@ -41,6 +41,10 @@ public function setUp() {
 
         $client = new MongoClient();
         $client->selectDB($this->databaseName)->drop();
+        $client->selectCollection($this->databaseName, 'image')->createIndex(
+            array('user' => 1, 'imageIdentifier' => 1),
```
Comment (christeredvartsen) [inline tests/phpunit/integration/Database/MongoDBTest.php]: `['user' => 1, 'imageIdentifier' => 1]`

File: tests/phpunit/integration/Database/MongoTest.php [hunk 5]
```diff
@@ -41,6 +41,10 @@ public function setUp() {
 
         $client = new MongoClient();
         $client->dropDatabase($this->databaseName);
+        $client->selectCollection($this->databaseName, 'image')->createIndex(
+            array('user' => 1, 'imageIdentifier' => 1),
```
Comment (christeredvartsen) [inline tests/phpunit/integration/Database/MongoTest.php]: `['user' => 1, 'imageIdentifier' => 1]`

File: src/Resource/Images.php (hunk 2 above)
Comment (matslindh) [inline src/Resource/Images.php]: The previous retrier used 100, and it's just a good number as anything. Can be 42. 98. 2^48. But not pi - that's too few retries (in general, 100 is many, but probably not too many for a server to handle _if_ there are lots of collisions.

**Comment by christeredvartsen** [comment]
The exception that Doctrine ends up throwing on a unique constraint violation depends on how the connection is generated. Consider the following example (the table used has a unique constraint on the `user` field, and can be considered empty when the connections in the example are made):

```php
<?php
$db = Doctrine\DBAL\DriverManager::getConnection([
    'pdo' => new PDO('sqlite::memory:'),
]);
$db->insert('test', ['id' => 1, 'user' => 'user']);
$db->insert('test', ['id' => 2, 'user' => 'user']); // throws Doctrine\DBAL\DBALException

$db = Doctrine\DBAL\DriverManager::getConnection([
    'dbname' => ':memory:', 
    'driver' => 'pdo_sqlite',
]);        
$db->insert('test', ['id' => 1, 'user' => 'user']);
$db->insert('test', ['id' => 2, 'user' => 'user']); // throws Doctrine\DBAL\Exception\UniqueConstraintViolationException
```

The code and message parts of the exceptions are the same in both examples. The same applies when connecting to a MySQL database.

The Doctrine database adapter in Imbo simply passes the configuration parameter to the `Doctrine\DBAL\DriverManager::getConnection` class. Perhaps we shall restrict this and require the second form in the example above to get more clear exceptions?

**Comment by matslindh** [comment]
Agreed. Removal of providing the PDO object directly in 3.0 sounds like a plan, although we should deprecate it first. We could do that in a 2.x-release, seeing as keeping it around will lead to duplicated code (although not too much as it's generally limited to this changeset).

**Comment by matslindh** [comment]
👍
